language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test-ci
  - vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpcs --standard=psr2 src/

after_success:
  - bash <(curl -s https://codecov.io/bash)
