language: php

php:
 - 7.1
 - 7.2
 - 7.3
 - nightly

cache:
 directories:
  - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - composer test-ci
 - vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
 - vendor/bin/phpcs --standard=psr2 src -spn
 - vendor/bin/phpcs --standard=phpcs.xml src -spn
 - vendor/bin/phpcs --standard=codor.xml src -spn

after_success:
 - bash <(curl -s https://codecov.io/bash)
