language: php

php:
 - 7.1
 - 7.2
 - 7.3
 - 7.4
# - nightly
# php8 requires dependencies updates which do not support version 7.3
# phploc/phploc , sebastian/version , phpunit/phpunit

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test-ci
  - vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpcs --standard=psr2 src/

after_success:
  - bash <(curl -s https://codecov.io/bash)
