language: php
os: linux
dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: 7.1
    - php: 7.4
  fast_finish: true


install:
  - COMPOSER_FLAGS="--no-interaction --prefer-source"
  - travis_retry composer install $COMPOSER_FLAGS

script:
  - composer test-ci
  - vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpcs --standard=psr2 src/

after_success:
  - bash <(curl -s https://codecov.io/bash)
