name: "Continuous Integration"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'img/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'img/**'

jobs:
  tests:
    name: "CI"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --prefer-dist"

      - name: "Run tests"
        run: "vendor/bin/simple-phpunit --colors=always --testdox"

      - name: "Run Churn"
        run: "php bin/churn run src -p -vvv"

  test-hg:
    name: "Test Mercurial"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-8.0-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-8.0-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --prefer-dist"

      - name: "Build Docker image"
        run: "docker build -t mercurial -f .docker/mercurial/Dockerfile .docker/mercurial"

      - name: "Run tests"
        run: |
          docker run -i --rm -v $PWD:/churn mercurial /churn/vendor/bin/simple-phpunit -c /churn/phpunit.xml.dist /churn/tests/EndToEnd/MercurialTest.php --coverage-clover=/churn/coverage-mercurial.xml
          sed -i 's/\/churn\/src/\/home\/runner\/work\/${{ github.event.repository.name }}\/${{ github.event.repository.name }}\/src/g' coverage-mercurial.xml

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-mercurial
          path: ./coverage-mercurial.xml

  analysis:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    needs: [test-hg]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "7.4"
          tools: composer:v2, composer-normalize

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-7.4-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-7.4-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --prefer-dist"

      - name: "Run tests"
        run: "composer test"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run --no-check-lock --no-update-lock"

      - uses: actions/download-artifact@v2
        with:
          name: coverage-mercurial
          path: ./coverage-mercurial

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml,./coverage-mercurial/coverage-mercurial.xml
          fail_ci_if_error: true
          verbose: true

  build:
    name: "Build Phar"
    runs-on: ubuntu-latest
    needs: [tests, analysis]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.2"
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-7.1-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-7.1-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies"
        run: |
          composer config platform.php 7.1.3
          composer update --no-dev --no-interaction --no-progress --prefer-dist
          composer config --unset platform.php

      - name: "Download Box"
        run: |
          curl -sL https://github.com/box-project/box/releases/download/3.9.1/box.phar -o box.phar
          chmod +x box.phar

      - name: "Validate box configuration"
        run: ./box.phar validate

      - name: "Compile"
        run: ./box.phar compile

      - name: "Test Version"
        run: diff -u <(bin/churn -V) <(./churn.phar -V)

      - name: "Test Phar"
        run: diff -u <(bin/churn run src --format=csv | sort) <(./churn.phar run src --format=csv | sort)

      - name: "Save Phar"
        uses: actions/upload-artifact@v2
        with:
          name: churn.phar
          path: ./churn.phar
          if-no-files-found: error
